### ISSUE TITLE
winrm or ssh transport

### ISSUE THREAD

**Issue by ejaronne** [mitre/mongodb-enterprise-advanced-3-stig-baseline#1]
The README mentions winrm. is that the typical transport, or is this on a linux box and needs ssh?

**Comment by HackerShark** [comment]
Add updated instructions showing command for running profile on windows target using winrm and linux target using ssh since mongodb can run on both.  

ex. Windows:  
```inspec exec https://github.com/mitre/mongodb-enterprise-advanced-stig-baseline/archive/master.tar.gz -t winrm://<hostip> --user '<admin-account>' --password=<password> --reporter cli json:<filename>.json```

ex. Linux:  
```inspec exec https://github.com/mitre/mongodb-enterprise-advanced-stig-baseline/archive/master.tar.gz -t ssh://<hostip> --user '<admin-account>' --password=<password> --reporter cli json:<filename>.json```
